{
 "title": "Mikrotik Montlevic Hangar",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "192.168.0.88 - CRS112-8G-4S", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "uptime .0.88",
   "type": "stat",
   "gridPos": { "h": 2, "w": 18, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TimeTicks{instance=\"192.168.0.88\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": ".88 temperature",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "mtxrHlTemperature{instance=\"192.168.0.88\"} / 10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 3 },
   "targets": [
    {
     "expr": "ZusedMemory{instance=\"192.168.0.88\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "mtxrHlVoltage{instance=\"192.168.0.88\"} / 10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SFP11 TX Errors",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrInterfaceStatsTxCollision{instance=\"192.168.0.88\", ifName=\"sfp11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mtxrInterfaceStatsTxDeferred{instance=\"192.168.0.88\", ifName=\"sfp11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mtxrInterfaceStatsTxDrop{instance=\"192.168.0.88\", ifName=\"sfp11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mtxrInterfaceStatsTxFCSError{instance=\"192.168.0.88\", ifName=\"sfp11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mtxrInterfaceStatsTxTotalCollision{instance=\"192.168.0.88\", ifName=\"sfp11\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SFP11 RX Errors",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrInterfaceStatsRxAlignError{instance=\"192.168.0.88\", ifName=\"sfp11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mtxrInterfaceStatsRxCarrierError{instance=\"192.168.0.88\", ifName=\"sfp11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mtxrInterfaceStatsRxCodeError{instance=\"192.168.0.88\", ifName=\"sfp11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mtxrInterfaceStatsRxControl{instance=\"192.168.0.88\", ifName=\"sfp11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mtxrInterfaceStatsRxDrop{instance=\"192.168.0.88\", ifName=\"sfp11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mtxrInterfaceStatsRxFCSError{instance=\"192.168.0.88\", ifName=\"sfp11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mtxrInterfaceStatsRxLengthError{instance=\"192.168.0.88\", ifName=\"sfp11\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SFP11 RX Errors",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "mtxrInterfaceStatsRxAlignError{instance=\"192.168.0.88\", ifName=\"sfp11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mtxrInterfaceStatsRxCarrierError{instance=\"192.168.0.88\", ifName=\"sfp11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mtxrInterfaceStatsRxCodeError{instance=\"192.168.0.88\", ifName=\"sfp11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mtxrInterfaceStatsRxControl{instance=\"192.168.0.88\", ifName=\"sfp11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mtxrInterfaceStatsRxDrop{instance=\"192.168.0.88\", ifName=\"sfp11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mtxrInterfaceStatsRxFCSError{instance=\"192.168.0.88\", ifName=\"sfp11\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mtxrInterfaceStatsRxLengthError{instance=\"192.168.0.88\", ifName=\"sfp11\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Interface Stats Bytes .88",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 23, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(mtxrInterfaceStatsRxBytes{instance=\"192.168.0.88\", ifName=\"sfp11\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(mtxrInterfaceStatsRxBytes{instance=\"192.168.0.88\", ifName=\"ether1\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(mtxrInterfaceStatsTxBytes{instance=\"192.168.0.88\", ifName=\"sfp11\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(mtxrInterfaceStatsTxBytes{instance=\"192.168.0.88\", ifName=\"ether1\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Driver Tx/Rx",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "rate(mtxrInterfaceStatsDriverRxBytes{instance=\"192.168.0.88\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(mtxrInterfaceStatsDriverTxBytes{instance=\"192.168.0.88\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Driver Tx/Rx packet",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "rate(mtxrInterfaceStatsDriverRxPackets{instance=\"192.168.0.88\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(mtxrInterfaceStatsDriverTxPackets{instance=\"192.168.0.88\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Interfaces Stats",
   "type": "table",
   "gridPos": { "h": 15, "w": 11, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "mtxrInterfaceStatsTxBytes{instance=\"192.168.0.88\"}"
    },
    {
     "expr": "mtxrInterfaceStatsRxBytes{instance=\"192.168.0.88\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mtxrInterfaceStatsLinkDowns{instance=\"192.168.0.88\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "192.168.0.4 - CSS106-1G-4P-1S - SwOS v2.18",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 }
  },
  {
   "title": "uptime .0.4",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 86 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TimeTicks{instance=\"192.168.0.4\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": ".04 temperature",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "mtxrHlTemperature{instance=\"192.168.0.4\"} / 10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SFP11 mtxrOptical ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "mtxrOpticalTemperature{instance=\"192.168.0.4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mtxrOpticalTxBiasCurrent{instance=\"192.168.0.4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mtxrOpticalWavelength{instance=\"192.168.0.4\"}/5000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mtxrOpticalSupplyVoltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "targets": [
    {
     "expr": "mtxrOpticalSupplyVoltage{instance=\"192.168.0.4\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}